In [1]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import compute_engine
from google.colab import drive
import pandas as pd

# Autenticar y conectar
from google.auth import default
creds, _ = default()
gc = gspread.authorize(creds)

ModuleNotFoundError: No module named 'google.colab'

In [ ]:
import pandas as pd

df_chipotle = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep="\t")
df_chipotle

In [ ]:
df_superstore = pd.read_csv('./1980-aula1/data/superstore_data.csv', sep=',')
df_superstore

In [ ]:
import chardet

# Detect the encoding of the file
with open('./1980-aula1/data/datos_sus.csv', 'rb') as file:
    detected_encoding = chardet.detect(file.read())['encoding']
print(detected_encoding)

In [ ]:
# Leemos solo las primeras 10 líneas para inspeccionar y detectar filas que no se necesitan
with open('./1980-aula1/data/datos_sus.csv', 'r', encoding='ISO-8859-1') as f:
    for i in range(5):
        print(f"Fila {i}: {f.readline()}")

In [ ]:
df_datos_sus = pd.read_csv('./1980-aula1/data/datos_sus.csv', sep=';', skiprows=3, encoding='ISO-8859-1')
df_datos_sus.tail(10)

In [ ]:
df_datos_sus = pd.read_csv('./1980-aula1/data/datos_sus.csv', sep=';', skiprows=3, skipfooter=9, encoding='ISO-8859-1')
df_datos_sus.tail()

In [ ]:
df_superstore = pd.read_csv('./1980-aula1/data/superstore_data.csv', sep=',', nrows=5)
df_superstore

In [ ]:
df_superstore = pd.read_csv('./1980-aula1/data/superstore_data.csv', sep=',', usecols=['Id', 'Year_Birth', 'Education', 'Marital_Status', 'Income'], nrows=5)
df_superstore

In [ ]:
df_superstore = pd.read_csv('./1980-aula1/data/superstore_data.csv', sep=',', usecols=[0,1,2,3,4], nrows=5)
df_superstore

In [ ]:
df_superstore.to_csv('./1980-aula1/data/df_superstore_5x5.csv', sep=';', index=False)

# Excel

In [ ]:
df_emisiones_C02 = pd.read_excel('./1980-aula2/data/emisiones_CO2.xlsx', sheet_name='emisiones_C02')
df_emisiones_C02

In [ ]:
pd.ExcelFile('./1980-aula2/data/emisiones_CO2.xlsx').sheet_names

In [ ]:
df_emisiones__percapita = pd.read_excel('./1980-aula2/data/emisiones_CO2.xlsx', sheet_name='emisiones_percapita')
df_emisiones__percapita.tail(10)

In [ ]:
df_fuentes = pd.read_excel('./1980-aula2/data/emisiones_CO2.xlsx', sheet_name='fuentes')
df_fuentes.sample(10)

In [ ]:
df_emisiones_C02_interval = pd.read_excel('./1980-aula2/data/emisiones_CO2.xlsx', sheet_name='emisiones_C02', usecols=[0,1,2,3,4], nrows=100)
df_emisiones_C02_interval

In [ ]:
df_emisiones_C02_interval.to_excel('./1980-aula2/data/df_emisiones_C02_interval.xlsx', index=False)

# Cargar en Google Colab

In [ ]:
# link = 'https://docs.google.com/spreadsheets/d/1Zq7EXpdvJRu5x1BUkiJiHLMZbAgyexouQ6Y--0PnwbI/edit?gid=650625061#gid=650625061'
# sheet_id = '1Zq7EXpdvJRu5x1BUkiJiHLMZbAgyexouQ6Y--0PnwbI'
# sheet_name = 'ESTACIONES'
# url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'
# df_emisiones_C02 = pd.read_csv(url)
# df_emisiones_C02

# Banco de datos SQL

In [3]:
import pandas as pd
import sqlalchemy as sq
from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [4]:
# 1. Creamos el engine
# engine_1 = create_engine('postgresql://postgres:postgres@localhost:5432/postgres')
engine_2 = create_engine('sqlite:///:memory:') # En memoria

In [8]:
# Para poder guardar un sql, la informacion debe ser tipo dataframe.
# df_emisiones_C02.to_sql('emisiones_C02', engine_1, index=False) 
# Para guardar un csv en sql, se debe primero pasar a dataframe
datos_csv = pd.read_csv('./1980-aula1/data/superstore_data.csv')
datos_csv

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10142,1976,PhD,Divorced,66476.0,0,1,7/3/2013,99,372,...,47,48,78,2,5,2,11,4,0,0
2236,5263,1977,2n Cycle,Married,31056.0,1,0,1/22/2013,99,5,...,3,8,16,1,1,0,3,8,0,0
2237,22,1976,Graduation,Divorced,46310.0,1,0,3/12/2012,99,185,...,15,5,14,2,6,1,5,8,0,0
2238,528,1978,Graduation,Married,65819.0,0,0,11/29/2012,99,267,...,149,165,63,1,5,4,10,3,0,0
2239,4070,1969,PhD,Married,94871.0,0,2,1/9/2012,99,169,...,188,0,144,1,8,5,4,7,1,0

In [9]:
datos_csv.to_sql('superstore_df', engine_2, index=False)

2240

In [10]:
inspector = inspect(engine_2)
inspector.get_table_names()

['./1980-aula1/data/superstore_df', 'superstore_df']

In [12]:
query = text('SELECT * FROM superstore_df WHERE Education = "Graduation" AND Year_Birth > 1970')
df = pd.read_sql(query, engine_2)
df

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
1,2964,1981,Graduation,Married,26872.0,0,0,10/16/2013,0,3,...,3,16,32,1,1,1,2,6,0,0
2,837,1977,Graduation,Married,54809.0,1,1,11/9/2013,0,63,...,13,13,22,4,2,1,5,4,0,0
3,10521,1977,Graduation,Married,54809.0,1,1,11/9/2013,0,63,...,13,13,22,4,2,1,5,4,1,0
4,9687,1975,Graduation,Single,73170.0,0,0,5/31/2014,1,184,...,50,30,32,1,5,4,6,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558,8595,1973,Graduation,Widow,42429.0,0,1,11/2/2014,99,55,...,2,0,4,2,1,1,3,5,0,0
559,7232,1973,Graduation,Widow,42429.0,0,1,11/2/2014,99,55,...,2,0,4,2,1,1,3,5,0,0
560,9977,1973,Graduation,Divorced,78901.0,0,1,9/17/2013,99,321,...,33,26,34,3,9,3,5,4,0,0
561,22,1976,Graduation,Divorced,46310.0,1,0,3/12/2012,99,185,...,15,5,14,2,6,1,5,8,0,0
562,528,1978,Graduation,Married,65819.0,0,0,11/29/2012,99,267,...,149,165,63,1,5,4,10,3,0,0

In [13]:
df.to_sql('superstore_df_2_grad', engine_2, index=False)

563

In [15]:
inspector = inspect(engine_2)
inspector.get_table_names()

['./1980-aula1/data/superstore_df', 'superstore_df', 'superstore_df_2_grad']

In [20]:
pd.read_sql('superstore_df_2_grad', engine_2, columns=['Id', 'Year_Birth', 'Education', 'Marital_Status', 'Income'])

        Id  Year_Birth   Education Marital_Status   Income
0     5371        1989  Graduation         Single  21474.0
1     2964        1981  Graduation        Married  26872.0
2      837        1977  Graduation        Married  54809.0
3    10521        1977  Graduation        Married  54809.0
4     9687        1975  Graduation         Single  73170.0
..     ...         ...         ...            ...      ...
558   8595        1973  Graduation          Widow  42429.0
559   7232        1973  Graduation          Widow  42429.0
560   9977        1973  Graduation       Divorced  78901.0
561     22        1976  Graduation       Divorced  46310.0
562    528        1978  Graduation        Married  65819.0

[563 rows x 5 columns]

In [21]:
pd.read_sql('superstore_df_2_grad', engine_2, columns=[0, 1, 2, 3, 4])

        Id  Year_Birth   Education Marital_Status   Income
0     5371        1989  Graduation         Single  21474.0
1     2964        1981  Graduation        Married  26872.0
2      837        1977  Graduation        Married  54809.0
3    10521        1977  Graduation        Married  54809.0
4     9687        1975  Graduation         Single  73170.0
..     ...         ...         ...            ...      ...
558   8595        1973  Graduation          Widow  42429.0
559   7232        1973  Graduation          Widow  42429.0
560   9977        1973  Graduation       Divorced  78901.0
561     22        1976  Graduation       Divorced  46310.0
562    528        1978  Graduation        Married  65819.0

[563 rows x 5 columns]

In [28]:
query = text('SELECT * FROM superstore_df WHERE Education = "Graduation" AND Year_Birth > 1970')
df = pd.read_sql(query, engine_2)    
df

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
1,2964,1981,Graduation,Married,26872.0,0,0,10/16/2013,0,3,...,3,16,32,1,1,1,2,6,0,0
2,837,1977,Graduation,Married,54809.0,1,1,11/9/2013,0,63,...,13,13,22,4,2,1,5,4,0,0
3,10521,1977,Graduation,Married,54809.0,1,1,11/9/2013,0,63,...,13,13,22,4,2,1,5,4,1,0
4,9687,1975,Graduation,Single,73170.0,0,0,5/31/2014,1,184,...,50,30,32,1,5,4,6,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558,8595,1973,Graduation,Widow,42429.0,0,1,11/2/2014,99,55,...,2,0,4,2,1,1,3,5,0,0
559,7232,1973,Graduation,Widow,42429.0,0,1,11/2/2014,99,55,...,2,0,4,2,1,1,3,5,0,0
560,9977,1973,Graduation,Divorced,78901.0,0,1,9/17/2013,99,321,...,33,26,34,3,9,3,5,4,0,0
561,22,1976,Graduation,Divorced,46310.0,1,0,3/12/2012,99,185,...,15,5,14,2,6,1,5,8,0,0
562,528,1978,Graduation,Married,65819.0,0,0,11/29/2012,99,267,...,149,165,63,1,5,4,10,3,0,0

In [31]:
# Borrar registros.
from sqlalchemy.exc import SQLAlchemyError

query = text('DELETE FROM superstore_df WHERE Id = 0 or Id = 1')
try:
    r_set = engine_2.connect().execute(query)
except SQLAlchemyError as e:
    print(e)
else:
    print("Registros borrados exitosamente.", r_set.rowcount)

Registros borrados exitosamente. 2

In [32]:

df = pd.read_sql('superstore_df', engine_2)    
df

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
2,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
3,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
4,7348,1958,PhD,Single,71691.0,0,0,3/17/2014,0,336,...,240,32,43,1,4,7,5,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2233,10142,1976,PhD,Divorced,66476.0,0,1,7/3/2013,99,372,...,47,48,78,2,5,2,11,4,0,0
2234,5263,1977,2n Cycle,Married,31056.0,1,0,1/22/2013,99,5,...,3,8,16,1,1,0,3,8,0,0
2235,22,1976,Graduation,Divorced,46310.0,1,0,3/12/2012,99,185,...,15,5,14,2,6,1,5,8,0,0
2236,528,1978,Graduation,Married,65819.0,0,0,11/29/2012,99,267,...,149,165,63,1,5,4,10,3,0,0
2237,4070,1969,PhD,Married,94871.0,0,2,1/9/2012,99,169,...,188,0,144,1,8,5,4,7,1,0

In [33]:
# Cambiar un registro.
from sqlalchemy.exc import SQLAlchemyError

query = text('UPDATE superstore_df SET Education = "Master" WHERE Id = 22')
try:
    r_set = engine_2.connect().execute(query)
except SQLAlchemyError as e:
    print(e)
else:
    print("Registros actualizados exitosamente.", r_set.rowcount)

Registros actualizados exitosamente. 1

In [34]:
df = pd.read_sql('superstore_df', engine_2)    
df

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10142,1976,PhD,Divorced,66476.0,0,1,7/3/2013,99,372,...,47,48,78,2,5,2,11,4,0,0
2236,5263,1977,2n Cycle,Married,31056.0,1,0,1/22/2013,99,5,...,3,8,16,1,1,0,3,8,0,0
2237,22,1976,Master,Divorced,46310.0,1,0,3/12/2012,99,185,...,15,5,14,2,6,1,5,8,0,0
2238,528,1978,Graduation,Married,65819.0,0,0,11/29/2012,99,267,...,149,165,63,1,5,4,10,3,0,0
2239,4070,1969,PhD,Married,94871.0,0,2,1/9/2012,99,169,...,188,0,144,1,8,5,4,7,1,0

In [35]:
inspector = inspect(engine_2)
inspector.get_table_names()

['./1980-aula1/data/superstore_df', 'superstore_df', 'superstore_df_2_grad']